# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables: 
  # Web app name
  webAppName: 'mavenapp'

  # Environment name
  environmentName: 'maven'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
      - task: UseJavaVersion@1
        displayName: 'Set up JDK 17'
        inputs:
          versionSpec: '17'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
          jdkFile: ''

      - task: Maven@4
        displayName: 'Maven Package'
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '17' 
          jdkArchitectureOption: 'x64'
          codeCoverageToolOption: None
          publishJUnitResults: true
          testResultsFiles: '$(System.DefaultWorkingDirectory)/**/surefire-reports/*.xml'
          goals: 'clean package'

      - task: CopyFiles@2
        displayName: 'Copy Files to artifact staging directory'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/target/*.?(war|jar)'
          TargetFolder: $(Build.ArtifactStagingDirectory)

      - upload: $(Build.ArtifactStagingDirectory)
        artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: {{ webAppName }}'
            inputs:
              azureSubscription: 'aug14'
              appType: 'webAppLinux'
              appName: 'mavenapp'
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'

